# Generated by Django 5.1.7 on 2025-04-21 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_video_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
    ]
