# Generated by Django 5.1.7 on 2025-04-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_generated',
            field=models.BooleanField(default=False),
        ),
    ]
