from ..video.generate_video import get_sentence_starts

if __name__ == "__main__":
    test_script = """<HOOK>Stray dogs in Yangon, Myanmar, 200,000 of them! Imagine a city where over two hundred thousand dogs are roaming freely without any control. These majestic creatures are not just mans companions; they have their own homes and lives. But controlling them? Its a puzzle that has been stumping governments for years.</HOOK>
<BODY>The struggle to manage stray dogs in Yangon is nothing short of monumental. The city alone hosts over 200,000 strays, each with its own story and challenges. Traditional methods like poisoning meat to control them have been tried before but face fierce opposition from animal lovers. These individuals hold strong beliefs that could be tied to their religious beliefs or the emotional bond they share with animals. Even so, these efforts often lead to harsh consequences for animals, making them a target of resistance.
Yangons municipal workers are now looking at alternative strategies, like spay-and-neuter programs. These initiatives involve capturing stray dogs, neutering and vaccinating them, and releasing them back into the wild. While this approach has shown promise in some areas like Jaipur, it hasnt been consistently implemented across Yangon due to funding issues and the need for follow-up efforts. Despite these hurdles, municipal workers are now focusing on spay-and-neuter programs in specific townships.
However, local officials remain skeptical about the long-term effectiveness of this program. They point to past failures caused by inconsistent funding and corruption. The problem is magnified by widespread corruption, making it difficult to ensure reliable implementation. Without sustainable follow-through, these efforts may end up being little more than empty gestures.
In conclusion, while spay-and-neuter programs hold potential, traditional culling methods remain impractical due to their animal impact and lack of long-term effectiveness. Balancing animal welfare with practicality is a significant challenge for Yangon as it works to manage its stray dog population effectively.</BODY>
<OUTRO>Yangons struggle with stray dogs is far from over. Its time to think about how we can ensure the welfare of these animals while finding sustainable solutions that truly benefit both humans and nature. What do you think? Can we find a way forward, or will this issue remain unresolved for generations? Lets discuss!</OUTRO>"""
    captions = [[
            "Stray",
            0.0,
            0.8
        ],
        [
            "dogs",
            0.8,
            1.08
        ],
        [
            "in",
            1.08,
            1.28
        ],
        [
            "Yangon, Myanmar, 200,000",
            1.28,
            2.84
        ],
        [
            "of",
            2.84,
            2.94
        ],
        [
            "them!",
            2.94,
            3.66
        ],
        [
            "Imagine",
            3.96,
            4.2
        ],
        [
            "a",
            4.2,
            4.34
        ],
        [
            "city",
            4.34,
            4.76
        ],
        [
            "where",
            4.76,
            5.0
        ],
        [
            "over",
            5.0,
            5.34
        ],
        [
            "two hundred thousand",
            5.34,
            6.04
        ],
        [
            "dogs",
            6.04,
            6.3
        ],
        [
            "are",
            6.3,
            6.54
        ],
        [
            "roaming",
            6.54,
            6.76
        ],
        [
            "freely",
            6.76,
            7.16
        ],
        [
            "without",
            7.16,
            7.5
        ],
        [
            "any",
            7.5,
            7.9
        ],
        [
            "control.",
            7.9,
            8.38
        ],
        [
            "These",
            8.76,
            8.96
        ],
        [
            "majestic",
            8.96,
            9.42
        ],
        [
            "creatures",
            9.42,
            9.86
        ],
        [
            "are",
            9.86,
            10.18
        ],
        [
            "not",
            10.18,
            10.44
        ],
        [
            "just",
            10.44,
            10.76
        ],
        [
            "mans companions;",
            10.76,
            11.56
        ],
        [
            "they",
            11.8,
            11.96
        ],
        [
            "have",
            11.96,
            12.16
        ],
        [
            "their",
            12.16,
            12.42
        ],
        [
            "own",
            12.42,
            12.62
        ],
        [
            "homes",
            12.62,
            12.92
        ],
        [
            "and",
            12.92,
            13.22
        ],
        [
            "lives.",
            13.22,
            13.64
        ],
        [
            "But",
            13.94,
            14.16
        ],
        [
            "controlling",
            14.16,
            14.58
        ],
        [
            "them? Its",
            14.58,
            15.54
        ],
        [
            "a",
            15.54,
            15.64
        ],
        [
            "puzzle",
            15.64,
            15.88
        ],
        [
            "that",
            15.88,
            16.06
        ],
        [
            "has",
            16.06,
            16.3
        ],
        [
            "been",
            16.3,
            16.5
        ],
        [
            "stumping",
            16.5,
            16.84
        ],
        [
            "governments",
            16.84,
            17.26
        ],
        [
            "for",
            17.26,
            17.54
        ],
        [
            "years.",
            17.54,
            17.84
        ],
        [
            "The",
            18.38,
            18.56
        ],
        [
            "struggle",
            18.56,
            18.78
        ],
        [
            "to",
            18.78,
            19.06
        ],
        [
            "manage",
            19.06,
            19.3
        ],
        [
            "stray",
            19.3,
            19.64
        ],
        [
            "dogs",
            19.64,
            20.0
        ],
        [
            "in",
            20.0,
            20.2
        ],
        [
            "Yangon",
            20.2,
            20.6
        ],
        [
            "is",
            20.6,
            20.86
        ],
        [
            "nothing",
            20.86,
            21.12
        ],
        [
            "short",
            21.12,
            21.52
        ],
        [
            "of",
            21.52,
            21.76
        ],
        [
            "monumental.",
            21.76,
            22.34
        ],
        [
            "The",
            22.78,
            22.88
        ],
        [
            "city",
            22.88,
            23.2
        ],
        [
            "alone",
            23.2,
            23.54
        ],
        [
            "hosts",
            23.54,
            23.92
        ],
        [
            "over",
            23.92,
            24.36
        ],
        [
            "200,000",
            24.36,
            25.28
        ],
        [
            "strays,",
            25.28,
            25.86
        ],
        [
            "each",
            25.94,
            26.32
        ],
        [
            "with",
            26.32,
            26.54
        ],
        [
            "its",
            26.54,
            26.72
        ],
        [
            "own",
            26.72,
            27.04
        ],
        [
            "story",
            27.04,
            27.38
        ],
        [
            "and",
            27.38,
            27.68
        ],
        [
            "challenges.",
            27.68,
            28.16
        ],
        [
            "Traditional",
            28.16,
            29.0
        ],
        [
            "methods",
            29.0,
            29.34
        ],
        [
            "like",
            29.34,
            29.6
        ],
        [
            "poisoning",
            29.6,
            29.98
        ],
        [
            "meat",
            29.98,
            30.24
        ],
        [
            "to",
            30.24,
            30.46
        ],
        [
            "control",
            30.46,
            30.74
        ],
        [
            "them",
            30.74,
            30.88
        ],
        [
            "have",
            30.88,
            31.02
        ],
        [
            "been",
            31.02,
            31.24
        ],
        [
            "tried",
            31.24,
            31.46
        ],
        [
            "before",
            31.46,
            31.8
        ],
        [
            "but",
            31.9,
            32.06
        ],
        [
            "face",
            32.06,
            32.34
        ],
        [
            "fierce",
            32.34,
            32.6
        ],
        [
            "opposition",
            32.6,
            33.0
        ],
        [
            "from",
            33.0,
            33.38
        ],
        [
            "animal",
            33.38,
            33.74
        ],
        [
            "lovers.",
            33.74,
            34.08
        ],
        [
            "These",
            34.66,
            34.84
        ],
        [
            "individuals",
            34.84,
            35.32
        ],
        [
            "hold",
            35.32,
            35.82
        ],
        [
            "strong",
            35.82,
            36.18
        ],
        [
            "beliefs",
            36.18,
            36.5
        ],
        [
            "that",
            36.5,
            36.68
        ],
        [
            "could",
            36.68,
            36.86
        ],
        [
            "be",
            36.86,
            37.06
        ],
        [
            "tied",
            37.06,
            37.2
        ],
        [
            "to",
            37.2,
            37.36
        ],
        [
            "their",
            37.36,
            37.56
        ],
        [
            "religious",
            37.56,
            37.86
        ],
        [
            "beliefs",
            37.86,
            38.24
        ],
        [
            "or",
            38.24,
            38.42
        ],
        [
            "the",
            38.42,
            38.62
        ],
        [
            "emotional",
            38.62,
            38.98
        ],
        [
            "bond",
            38.98,
            39.18
        ],
        [
            "they",
            39.18,
            39.46
        ],
        [
            "share",
            39.46,
            39.58
        ],
        [
            "with",
            39.58,
            39.86
        ],
        [
            "animals.",
            39.86,
            40.3
        ],
        [
            "Even",
            40.62,
            40.86
        ],
        [
            "so,",
            40.86,
            41.26
        ],
        [
            "these",
            41.54,
            41.6
        ],
        [
            "efforts",
            41.6,
            41.94
        ],
        [
            "often",
            41.94,
            42.34
        ],
        [
            "lead",
            42.34,
            42.5
        ],
        [
            "to",
            42.5,
            42.72
        ],
        [
            "harsh",
            42.72,
            42.92
        ],
        [
            "consequences",
            42.92,
            43.48
        ],
        [
            "for",
            43.48,
            43.72
        ],
        [
            "animals,",
            43.72,
            44.02
        ],
        [
            "making",
            44.26,
            44.38
        ],
        [
            "them",
            44.38,
            44.56
        ],
        [
            "a",
            44.56,
            44.76
        ],
        [
            "target",
            44.76,
            45.04
        ],
        [
            "of",
            45.04,
            45.3
        ],
        [
            "resistance.",
            45.3,
            45.92
        ],
        [
            "Yangons",
            46.64,
            47.04
        ],
        [
            "municipal",
            47.04,
            47.6
        ],
        [
            "workers",
            47.6,
            48.12
        ],
        [
            "are",
            48.12,
            48.38
        ],
        [
            "now",
            48.38,
            48.56
        ],
        [
            "looking",
            48.56,
            48.8
        ],
        [
            "at",
            48.8,
            49.02
        ],
        [
            "alternative",
            49.02,
            49.54
        ],
        [
            "strategies,",
            49.54,
            50.16
        ],
        [
            "like",
            50.54,
            50.7
        ],
        [
            "spay-and-neuter",
            50.7,
            51.38
        ],
        [
            "programs.",
            51.38,
            51.92
        ],
        [
            "These",
            52.3,
            52.62
        ],
        [
            "initiatives",
            52.62,
            53.1
        ],
        [
            "involve",
            53.1,
            53.46
        ],
        [
            "capturing",
            53.46,
            54.02
        ],
        [
            "stray",
            54.02,
            54.34
        ],
        [
            "dogs,",
            54.34,
            54.68
        ],
        [
            "neutering",
            54.68,
            55.26
        ],
        [
            "and",
            55.26,
            55.5
        ],
        [
            "vaccinating",
            55.5,
            56.04
        ],
        [
            "them,",
            56.04,
            56.3
        ],
        [
            "and",
            56.52,
            56.72
        ],
        [
            "releasing",
            56.72,
            57.12
        ],
        [
            "them",
            57.12,
            57.28
        ],
        [
            "back",
            57.28,
            57.54
        ],
        [
            "into",
            57.54,
            57.76
        ],
        [
            "the",
            57.76,
            57.94
        ],
        [
            "wild.",
            57.94,
            58.28
        ],
        [
            "While",
            59.02,
            59.26
        ],
        [
            "this",
            59.26,
            59.46
        ],
        [
            "approach",
            59.46,
            59.78
        ],
        [
            "has",
            59.78,
            60.0
        ],
        [
            "shown",
            60.0,
            60.2
        ],
        [
            "promise",
            60.2,
            60.52
        ],
        [
            "in",
            60.52,
            60.72
        ],
        [
            "some",
            60.72,
            60.94
        ],
        [
            "areas",
            60.94,
            61.38
        ],
        [
            "like",
            61.4,
            61.66
        ],
        [
            "Jaipur,",
            61.66,
            62.14
        ],
        [
            "it",
            62.26,
            62.46
        ],
        [
            "hasnt",
            62.46,
            62.82
        ],
        [
            "been",
            62.82,
            63.12
        ],
        [
            "consistently",
            63.12,
            63.54
        ],
        [
            "implemented",
            63.54,
            64.14
        ],
        [
            "across",
            64.14,
            64.44
        ],
        [
            "Yangon",
            64.44,
            64.84
        ],
        [
            "due",
            64.84,
            65.06
        ],
        [
            "to",
            65.06,
            65.2
        ],
        [
            "funding",
            65.2,
            65.5
        ],
        [
            "issues",
            65.5,
            65.94
        ],
        [
            "and",
            65.94,
            66.12
        ],
        [
            "the",
            66.12,
            66.2
        ],
        [
            "need",
            66.2,
            66.38
        ],
        [
            "for",
            66.38,
            66.64
        ],
        [
            "follow-up",
            66.64,
            67.1
        ],
        [
            "efforts.",
            67.1,
            67.64
        ],
        [
            "Despite",
            67.96,
            68.24
        ],
        [
            "these",
            68.24,
            68.54
        ],
        [
            "hurdles,",
            68.54,
            68.96
        ],
        [
            "municipal",
            69.5,
            69.78
        ],
        [
            "workers",
            69.78,
            70.22
        ],
        [
            "are",
            70.22,
            70.44
        ],
        [
            "now",
            70.44,
            70.7
        ],
        [
            "focusing",
            70.7,
            71.08
        ],
        [
            "on",
            71.08,
            71.32
        ],
        [
            "spay-and-neuter",
            71.32,
            71.96
        ],
        [
            "programs",
            71.96,
            72.42
        ],
        [
            "in",
            72.42,
            72.7
        ],
        [
            "specific",
            72.7,
            73.18
        ],
        [
            "townships.",
            73.18,
            74.14
        ],
        [
            "However,",
            74.24,
            74.8
        ],
        [
            "local",
            75.34,
            75.52
        ],
        [
            "officials",
            75.52,
            75.9
        ],
        [
            "remain",
            75.9,
            76.24
        ],
        [
            "skeptical",
            76.24,
            76.78
        ],
        [
            "about",
            76.78,
            77.0
        ],
        [
            "the",
            77.0,
            77.2
        ],
        [
            "long-term",
            77.2,
            77.7
        ],
        [
            "effectiveness",
            77.7,
            78.2
        ],
        [
            "of",
            78.2,
            78.46
        ],
        [
            "this",
            78.46,
            78.64
        ],
        [
            "program.",
            78.64,
            79.08
        ],
        [
            "They",
            79.6,
            79.9
        ],
        [
            "point",
            79.9,
            80.06
        ],
        [
            "to",
            80.06,
            80.3
        ],
        [
            "past",
            80.3,
            80.52
        ],
        [
            "failures",
            80.52,
            80.9
        ],
        [
            "caused",
            80.9,
            81.2
        ],
        [
            "by",
            81.2,
            81.42
        ],
        [
            "inconsistent",
            81.42,
            81.96
        ],
        [
            "funding",
            81.96,
            82.46
        ],
        [
            "and",
            82.46,
            82.84
        ],
        [
            "corruption.",
            82.84,
            83.36
        ],
        [
            "The",
            83.36,
            83.86
        ],
        [
            "problem",
            83.86,
            84.24
        ],
        [
            "is",
            84.24,
            84.54
        ],
        [
            "magnified",
            84.54,
            85.12
        ],
        [
            "by",
            85.12,
            85.36
        ],
        [
            "widespread",
            85.36,
            85.74
        ],
        [
            "corruption,",
            85.74,
            86.24
        ],
        [
            "making",
            86.58,
            86.6
        ],
        [
            "it",
            86.6,
            86.78
        ],
        [
            "difficult",
            86.78,
            87.24
        ],
        [
            "to",
            87.24,
            87.48
        ],
        [
            "ensure",
            87.48,
            87.78
        ],
        [
            "reliable",
            87.78,
            88.26
        ],
        [
            "implementation.",
            88.26,
            89.1
        ],
        [
            "Without",
            89.7,
            89.86
        ],
        [
            "sustainable",
            89.86,
            90.4
        ],
        [
            "follow-through,",
            90.4,
            91.12
        ],
        [
            "these",
            91.2,
            91.46
        ],
        [
            "efforts",
            91.46,
            91.66
        ],
        [
            "may",
            91.66,
            92.0
        ],
        [
            "end",
            92.0,
            92.2
        ],
        [
            "up",
            92.2,
            92.36
        ],
        [
            "being",
            92.36,
            92.52
        ],
        [
            "little",
            92.52,
            92.82
        ],
        [
            "more",
            92.82,
            93.06
        ],
        [
            "than",
            93.06,
            93.2
        ],
        [
            "empty",
            93.2,
            93.48
        ],
        [
            "gestures.",
            93.48,
            93.98
        ],
        [
            "In",
            94.62,
            94.68
        ],
        [
            "conclusion,",
            94.68,
            95.3
        ],
        [
            "while spay-and-neuter",
            95.74,
            96.58
        ],
        [
            "programs",
            96.58,
            97.18
        ],
        [
            "hold",
            97.18,
            97.58
        ],
        [
            "potential,",
            97.58,
            98.04
        ],
        [
            "traditional",
            98.38,
            98.6
        ],
        [
            "culling",
            98.6,
            98.98
        ],
        [
            "methods",
            98.98,
            99.26
        ],
        [
            "remain",
            99.26,
            99.72
        ],
        [
            "impractical",
            99.72,
            100.32
        ],
        [
            "due",
            100.32,
            100.58
        ],
        [
            "to",
            100.58,
            100.74
        ],
        [
            "their",
            100.74,
            101.0
        ],
        [
            "animal",
            101.0,
            101.26
        ],
        [
            "impact",
            101.26,
            101.72
        ],
        [
            "and",
            101.72,
            101.94
        ],
        [
            "lack",
            101.94,
            102.2
        ],
        [
            "of",
            102.2,
            102.46
        ],
        [
            "long-term",
            102.46,
            102.96
        ],
        [
            "effectiveness.",
            102.96,
            103.66
        ],
        [
            "Balancing",
            104.42,
            104.78
        ],
        [
            "animal",
            104.78,
            105.48
        ],
        [
            "welfare",
            105.48,
            106.02
        ],
        [
            "with",
            106.02,
            106.34
        ],
        [
            "practicality",
            106.34,
            107.2
        ],
        [
            "is",
            107.2,
            107.44
        ],
        [
            "a",
            107.44,
            107.56
        ],
        [
            "significant",
            107.56,
            108.1
        ],
        [
            "challenge",
            108.1,
            108.5
        ],
        [
            "for",
            108.5,
            108.72
        ],
        [
            "Yangon",
            108.72,
            109.08
        ],
        [
            "as",
            109.08,
            109.26
        ],
        [
            "it",
            109.26,
            109.4
        ],
        [
            "works",
            109.4,
            109.62
        ],
        [
            "to",
            109.62,
            109.84
        ],
        [
            "manage",
            109.84,
            110.06
        ],
        [
            "its",
            110.06,
            110.36
        ],
        [
            "stray",
            110.36,
            110.7
        ],
        [
            "dog",
            110.7,
            111.18
        ],
        [
            "population",
            111.18,
            111.86
        ],
        [
            "effectively.",
            111.86,
            112.5
        ],
        [
            "Yangons",
            113.38000000000001,
            113.98
        ],
        [
            "struggle",
            113.98,
            114.42
        ],
        [
            "with",
            114.42,
            114.86
        ],
        [
            "stray",
            114.86,
            115.12
        ],
        [
            "dogs",
            115.12,
            115.42
        ],
        [
            "is",
            115.42,
            115.72
        ],
        [
            "far",
            115.72,
            115.9
        ],
        [
            "from",
            115.9,
            116.18
        ],
        [
            "over.",
            116.18,
            116.54
        ],
        [
            "Its",
            117.06,
            117.36
        ],
        [
            "time",
            117.36,
            117.54
        ],
        [
            "to",
            117.54,
            117.72
        ],
        [
            "think",
            117.72,
            117.92
        ],
        [
            "about",
            117.92,
            118.12
        ],
        [
            "how",
            118.12,
            118.28
        ],
        [
            "we",
            118.28,
            118.46
        ],
        [
            "can",
            118.46,
            118.64
        ],
        [
            "ensure",
            118.64,
            118.88
        ],
        [
            "the",
            118.88,
            119.06
        ],
        [
            "welfare",
            119.06,
            119.34
        ],
        [
            "of",
            119.34,
            119.62
        ],
        [
            "these",
            119.62,
            119.8
        ],
        [
            "animals",
            119.8,
            120.22
        ],
        [
            "while",
            120.22,
            120.52
        ],
        [
            "finding",
            120.52,
            120.9
        ],
        [
            "sustainable",
            120.9,
            121.46
        ],
        [
            "solutions",
            121.46,
            122.04
        ],
        [
            "that",
            122.04,
            122.3
        ],
        [
            "truly",
            122.3,
            122.54
        ],
        [
            "benefit",
            122.54,
            122.96
        ],
        [
            "both",
            122.96,
            123.3
        ],
        [
            "humans",
            123.3,
            123.66
        ],
        [
            "and",
            123.66,
            123.96
        ],
        [
            "nature.",
            123.96,
            124.34
        ],
        [
            "What",
            124.8,
            124.88
        ],
        [
            "do",
            124.88,
            125.04
        ],
        [
            "you",
            125.04,
            125.24
        ],
        [
            "think?",
            125.24,
            125.46
        ],
        [
            "Can",
            125.9,
            126.42
        ],
        [
            "we",
            126.42,
            126.66
        ],
        [
            "find",
            126.66,
            126.9
        ],
        [
            "a",
            126.9,
            127.06
        ],
        [
            "way",
            127.06,
            127.18
        ],
        [
            "forward,",
            127.18,
            127.6
        ],
        [
            "or",
            127.6,
            127.88
        ],
        [
            "will",
            127.88,
            127.88
        ],
        [
            "this",
            127.88,
            128.18
        ],
        [
            "issue",
            128.18,
            128.36
        ],
        [
            "remain",
            128.36,
            128.74
        ],
        [
            "unresolved",
            128.74,
            129.2
        ],
        [
            "for",
            129.2,
            129.44
        ],
        [
            "generations?",
            129.44,
            129.96
        ],
        [
            "Let's",
            130.66,
            131.02
        ],
        [
            "discuss.",
            131.02,
            131.44
        ]
    ]
    print(get_sentence_starts(test_script, captions))